services:
  - type: web
    name: api-pos-jeffry
    env: php
    region: singapore
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8080
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false